import React from 'react';

const OtherServices = () => {
  const services = [
    {
      title: 'GeM Registration',
      description: 'GeM (Government e-Marketplace) is an online platform that allows businesses to engage in government procurement and tendering processes. We guide you through the complete process. This service will help you to explore and access valuable business opportunities within the public sector, and help you make your transactions with government entities, whether you are a manufacturer, supplier, or service provider.',
    },
    {
      title: 'EPR Registration',
      description: 'Extended Producer Responsibility (EPR) is a key environmental regulation that requires producers, importers, and brand owners to manage the end-of-life waste generated by their products. This process involves registering and operating your business under the EPR framework. Helping you comply with environmental laws while managing packaging waste effectively. This service is especially relevant for businesses that produce goods with packaging materials.',
    },
    {
      title: 'Trademark Registration',
      description: 'Your trademark represents your brand identity, and protecting it is crucial to safeguard your intellectual property. We help you through the process of registering your trademark, ensuring it is legally protected against unauthorized use or infringement. Our team will guide you from the initial application to final registration, providing comprehensive support in helping you secure exclusive rights to your brand name, logo, or slogan.',
    },
    {
      title: 'Foreign Bookkeeping',
      description: 'For businesses operating internationally, maintaining accurate financial records across borders can be complex. Our foreign bookkeeping services help ensure that your financial transactions are recorded accurately in compliance with both local and international accounting standards. Financial year closures, tax compliance, and regular reporting - our experts follow specific financial regulations in various countries; our services will ensure that your books are always in order.',
    },
  ];

  return (
    <div className="min-h-screen relative bg-gradient-to-br from-blue-50 to-orange-50">
      {/* Background logo pattern */}
      <div 
        className="absolute inset-0 z-20 opacity-10"
        style={{
          backgroundImage: `url('/logo.png')`,
          backgroundSize: '700px',
          backgroundPosition: 'center',
          backgroundRepeat: 'no-repeat',
        }}
      />
      
      {/* Content */}
      <div className="container mx-auto px-4 py-16 relative z-10">
        <h1 className="text-4xl font-bold text-center mb-12">Other Services</h1>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-x-36 gap-y-16">
          {services.map((service, index) => (
            <div
              key={index}
              className="bg-white/90 backdrop-blur-sm rounded-lg shadow-xl p-6 hover:shadow-xl transition-all duration-300 relative z-0"
            >
              <h2 className="text-2xl font-semibold mb-4">{service.title}</h2>
              <p className="text-gray-600 leading-relaxed">{service.description}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default OtherServices;
